# Weel2_授業前課題3_行列積のスクラッチ

以下のような行列A、Bを考えます。


$$
    \boldsymbol{A}=
        \left[\begin{matrix}
            -1 & 2 & 3 \\
            4 & -5 & 6 \\
            7 & 8 & -9
        \end{matrix}\right] \quad
    ,
    \boldsymbol{B}=
        \left[\begin{matrix}
            0 & 2 & 1 \\
            0 & 2 & -8 \\
            2 & 9 & -1
        \end{matrix}\right] \quad
$$


NumPyで表すと次のようになります。

    import numpy as np
    a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
    b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

## 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

$
    \boldsymbol{A}=
        \left(\begin{matrix}
            a_{11} & a_{12} & a_{13} \\
            a_{21} & a_{22} & a_{23} \\
            a_{31} & a_{32} & a_{33}
        \end{matrix}\right) \quad
    \boldsymbol{B}=
        \left(\begin{matrix}
            b_{11} & b_{12} & b_{13} \\
            b_{21} & b_{22} & b_{23} \\
            b_{31} & b_{32} & b_{33}
        \end{matrix}\right) \quad
    \boldsymbol{A} \times \boldsymbol{B}=
        \left(\begin{matrix}
            c_{11} & c_{12} & c_{13} \\
            c_{21} & c_{22} & c_{23} \\
            c_{31} & c_{32} & c_{33}
        \end{matrix}\right) \quad
$

$c_{11}=a_{11} \times b_{11} + a_{12} \times b_{21} + a_{13} \times b_{31}$
<br>
$c_{12}=a_{11} \times b_{12} + a_{12} \times b_{22} + a_{13} \times b_{32}$
<br>
$c_{13}=a_{11} \times b_{13} + a_{12} \times b_{23} + a_{13} \times b_{33}$
<br>
$c_{21}=a_{21} \times b_{11} + a_{22} \times b_{21} + a_{23} \times b_{31}$
<br>
$c_{22}=a_{21} \times b_{12} + a_{22} \times b_{22} + a_{23} \times b_{32}$
<br>
$c_{23}=a_{21} \times b_{13} + a_{22} \times b_{23} + a_{23} \times b_{33}$
<br>
$c_{31}=a_{31} \times b_{11} + a_{32} \times b_{21} + a_{33} \times b_{31}$
<br>
$c_{32}=a_{31} \times b_{12} + a_{32} \times b_{22} + a_{33} \times b_{32}$
<br>
$c_{33}=a_{31} \times b_{13} + a_{32} \times b_{23} + a_{33} \times b_{33}$

$
    \boldsymbol{A} \times \boldsymbol{B}=
        \left(\begin{matrix}
            6 & 29 & -20 \\
            12 & 52 & 38 \\
            -18 & -51 & -48
        \end{matrix}\right) \quad
$

## 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

> numpy.matmul — NumPy v1.16 Manual

> numpy.dot — NumPy v1.16 Manual

《3種類の違い》

np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。

今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。

> If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [2]:
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [3]:
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

1.行列Aの(0,0)の要素 $a_{0,0}$ と行列Bの(0,0)の要素 $b_{0,0}$ を掛け合わせる
<br>
2.行列Aの(0,1)の要素 $a_{0,1}$ と行列Bの(1,0)の要素 $b_{1,0}$ を掛け合わせる
<br>
行列Aの(0,2)の要素 $a_{0,2}$ と行列Bの(2,0)の要素 $b_{2,0}$ を掛け合わせる
<br>

それらの値を全て足し合わせる

数式で表すと
$$
\sum_{k=0}^{2} a_{0,k}b_{k,0}
$$
です。

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [4]:
matrix_lst = []
for i in range(3):
    a_row = a_ndarray[i, :]
    for j in range(3):
        b_column = b_ndarray[:, j]
        num = 0
        for a, b in zip(a_row, b_column):
            num += a * b
        matrix_lst.append(num)
np.array(matrix_lst).reshape(3, 3)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【問題4】行列積を行う関数の作成

問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


計算結果である $3 \times 3$ の行列Cの各要素 $c_{i,j}$  は数式で表すと次のようになります。
$$
c_{i,j}=\sum_{k=0}^{2} a_{i,k}b_{k,j}
$$

In [5]:
def matrix_product(a_matrix, b_matrix):
    rows = a_matrix.shape[0]
    columns = b_matrix.shape[1]
    matrix_lst = []
    for i in range(rows):
        a_row = a_matrix[i, :]
        for j in range(columns):
            b_column = b_matrix[:, j]
            num = 0
            for a, b in zip(a_row, b_column):
                num += a * b
            matrix_lst.append(num)
    matrix_product = np.array(matrix_lst).reshape(rows, columns)
    return matrix_product

In [6]:
matrix_product(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

次に以下のような例を考えます。

$$
    \boldsymbol{D}=
        \left[\begin{matrix}
            -1 & 2 & 3 \\
            4 & -5 & 6
        \end{matrix}\right] \quad
    ,
    \boldsymbol{E}=
        \left[\begin{matrix}
            -9 & 8 & 7 \\
            6 & -5 & 4
        \end{matrix}\right] \quad
$$


    d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
    e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

## 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [7]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [8]:
# エラー表示するように修正
def matrix_product(a_matrix, b_matrix):
    a_rows, a_columns = a_matrix.shape
    b_rows, b_columns = b_matrix.shape
    if a_columns != b_rows:
        return print('第一引数の列数と第二引数の行数が一致していないため、計算できません')
    matrix_lst = []
    for i in range(a_rows):
        a_row = a_matrix[i, :]
        for j in range(b_columns):
            b_column = b_matrix[:, j]
            num = 0
            for a, b in zip(a_row, b_column):
                num += a * b
            matrix_lst.append(num)
    matrix_product = np.array(matrix_lst).reshape(a_rows, b_columns)
    return matrix_product

In [9]:
matrix_product(d_ndarray, e_ndarray)

第一引数の列数と第二引数の行数が一致していないため、計算できません


## 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

> numpy.transpose — NumPy v1.16 Manual

> numpy.ndarray.T — NumPy v1.16 Manual

In [10]:
matrix_product(d_ndarray.T, e_ndarray)

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])

In [11]:
matrix_product(d_ndarray, e_ndarray.T)

array([[ 46,  -4],
       [-34,  73]])